name: AutoQueue

on: 
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: "0 2 * * *"
  watch:
    types: [started]
   
jobs:
  Run:
    runs-on: ubuntu-latest
    # runs-on: windows-2019
    # if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install requirements & webdriver
      run: |
        pip install -r requirements.txt
    - name: Run script
      env: 
        cookie: ${{ secrets.cookie }}
      run: |
        python3 main.py
